Restrict creating Power VS machine with negative processor and memory
openshift/machine-api-operator pull request #1067
Opened 2022-09-08 12:36 UTC by Karthik-K-N

Related to bug: https://issues.redhat.com/browse/OCPBUGS-1018

2022-09-08 14:18 UTC, Karthik-K-N commented
/cc  @mkumatag

2022-09-08 16:30 UTC, Karthik-K-N commented
/retest-required

2022-09-08 16:43 UTC, mkumatag requested changes
small change, otherwise lgtm

2022-09-08 16:43 UTC, mkumatag commented on pkg/webhooks/machine_webhook.go
> +		if processor < 0 {
This whole block can be written as
```golang
	if processor < 0 {
		errs = append(errs, field.Invalid(parentPath.Child("processor"), processor, "processor value cannot be negative"))
	} else if providerSpec.ProcessorType == machinev1.PowerVSProcessorTypeDedicated && processor < val.minProcessorDedicated {
		warnings = append(warnings, fmt.Sprintf("providerspec.Processor %f is less than the minimum value %f for providerSpec.ProcessorType: %s", processor, val.minProcessorDedicated, providerSpec.ProcessorType))
	} else if processor < val.minProcessorSharedCapped {
		warnings = append(warnings, fmt.Sprintf("providerspec.Processor %f is less than the minimum value %f for providerSpec.ProcessorType: %s", processor, val.minProcessorSharedCapped, providerSpec.ProcessorType))
	}
```

2022-09-13 09:32 UTC, Karthik-K-N commented
/retest-required

2022-09-13 09:32 UTC, Karthik-K-N commented
/cc @JoelSpeed

2022-09-13 10:25 UTC, JoelSpeed reviewed
Why does being less than the value not catch this? The minimum value should be positive right?

2022-09-13 10:38 UTC, Karthik-K-N commented
> Why does being less than the value not catch this? The minimum value should be positive right?

Currently if the user provided value is less than the recommended we just show the warning but not error out the request. So I have made the changes to error out incase the user provided value is negative.

2022-09-13 11:06 UTC, JoelSpeed commented
/lgtm
/approve

2022-09-13 11:10 UTC, Karthik-K-N commented
/retest-required

2022-09-16 05:32 UTC, Karthik-K-N commented
/retest-required

2022-09-16 12:24 UTC, Karthik-K-N commented
/retest-required

2022-09-19 09:14 UTC, Karthik-K-N commented
/retest-required

2022-09-23 13:12 UTC, Karthik-K-N commented
/retest-required

2022-09-27 11:53 UTC, Karthik-K-N commented
/retest-required

2022-09-30 12:31 UTC, JoelSpeed commented
/override ci/prow/e2e-aws-operator

Autoscaler test failed, known issue, unrelated to this PR, LGTM

2022-09-30 15:28 UTC, merged