Bug 1805639: Validate credentialsSecret
openshift/machine-api-operator pull request #673
Opened 2020-08-10 14:01 UTC by JoelSpeed

This let the webhook to validate the credentialsSecret existence before creating the machine resource.
Additionally we should probably reflect any unexpected error to use the credentialsSecret as providerStatus conditions https://issues.redhat.com/browse/OCPCLOUD-931

I'm taking over this bug from @enxebre as he is away for three weeks. I've applied all of my suggestions from the original PR #660 and am happy for this to merge once it has undergone some manual testing.

2020-08-10 14:23 UTC, JoelSpeed commented
> this looks reasonable to me, i just want to make sure i understand it. is the idea here that during validation for a machine create/update we check to ensure that the credentials secret exists and if not we add an error which causes a graceful failure?

Yep that's the plan, prevents someone from updating the secret to point to a secret that doesn't exist. Currently spinning up a cluster to test that this works as expected

2020-08-10 14:24 UTC, elmiko commented
thanks Joel, makes sense to me.
/approve

2020-08-10 16:07 UTC, JoelSpeed commented
I've manually tested this and can confirm, any secret that existed within the namespace was allowed, but a secret that did not exist was rejected with the appropriate message. I'm happy for this to merge once the tests pass

2020-08-17 11:27 UTC, JoelSpeed commented
> I don't think the webhook is the right way to solve this. I'd prefer to go immediately to failed if the credentials are invalid.

We shouldn't force the machine to `Failed` if the credentials are invalid since we can't check whether the VM exists or not (because no creds). If we forced it to failed because someone deleted the credentials after the Machine was created, this could cause a machine to go Failed when actually, it's still running.

> If someone deletes the secret later, it's going to be hard to troubleshoot what's happening.

Why does this change make it any harder to debug than the existing code?

> While this does marginally improve the UX when creating a machineset, it has a greater negative impact on troubleshooting down the road IMO.

This helps in a small way yes, it's trying to improve the UX at machineset creation time, but we can't catch all cases, and I don't think there's an easy way to catch all cases. 

I don't think this makes the experience worse than it already is, I don't think it should interfere with debugging etc. and since it doesn't affect any of the existing validations or behaviour, we aren't taking any reporting of errors away.

2020-08-18 14:41 UTC, JoelSpeed commented
/retest

2020-08-19 20:02 UTC, michaelgugino commented
Unless we're extending the machineSet to add some information to the machineSet.status object about why it can't create machines, I'm against this change.

This change will inevitably lead to "I created a machineset, but I don't have any machines" type of questions.  It won't be obvious what's broken or where to look.  Couple that with the fact that people use node/instance/machine all interchangeably, it's going to be hard to communicate to users where to look for what conditions.

As far as failing the machine due to invalid credentials, we should check to ensure that the machine wasn't provisioned already.  We could check this before we set finalizers, ensure the secret is present, if it is, we set finalizers, if it's not, we set failed (possibly skip setting finalizers?)  If finalizers are set, we have no way of knowing if an instance was created if credentials go missing (on the outside chance that the machine-controller crashes around the same time the credentials are removed and immediately after the request to create the instance was submitted).

2020-08-19 20:10 UTC, elmiko commented
it seems like there is debate to had about this still, i'm going to remove my approval until the issues raised here have been resolved.
/approve cancel

2020-08-20 10:49 UTC, JoelSpeed commented
> Unless we're extending the machineSet to add some information to the machineSet.status object about why it can't create machines, I'm against this change.

We could add a condition, and/or use an event to communicate this.

> This change will inevitably lead to "I created a machineset, but I don't have any machines" type of questions. It won't be obvious what's broken or where to look. Couple that with the fact that people use node/instance/machine all interchangeably, it's going to be hard to communicate to users where to look for what conditions.

If the MachineSet is accepted, then it will have a valid credentialsSecret, the only way you could end up with this is if the MachineSet is created and then the credentialsSecret is deleted at a later point. It's possible, so I agree, we should be adding some more obvious errors to the MachineSet events or status

> As far as failing the machine due to invalid credentials, we should check to ensure that the machine wasn't provisioned already. We could check this before we set finalizers, ensure the secret is present, if it is, we set finalizers, if it's not, we set failed (possibly skip setting finalizers?) If finalizers are set, we have no way of knowing if an instance was created if credentials go missing (on the outside chance that the machine-controller crashes around the same time the credentials are removed and immediately after the request to create the instance was submitted).

Your suggestion here is that we swap the ordering of checking the instance exists with the addition of the finalizer, so that we only add the finalizer after we successfully create the machine? I think this is likely to cause issues with Machine leaking. We had a bug recently with Azure where `Create` always returns an error initially due to the async nature of their API, so unless we are 100% sure we can determine the difference between a create failing legitimately and this async failure, then add the finalizer, we could possible leak an instance. 
Note how at the moment we add the finalizer and then requeue, this is to prevent conflict errors that might cause us to have created the machine but not committed the finalizer. Again this is leak prevention and I don't think we should be changing this. The finalizer needs to be on the Machine before we attempt to create the instance

2020-08-27 03:13 UTC, michaelgugino commented
> Your suggestion here is that we swap the ordering of checking the instance exists with the addition of the finalizer, so that we only add the finalizer after we successfully create the machine? I think this is likely to cause issues with Machine leaking.

Not quite.  My suggestion is to check that the credentials secret exists before adding the finalizer.  If it doesn't, we fail.  If the credentials secret exists, we add the finalizer, don't check it any more.  This way, if the secret disappears later we know there is a possibility that the machine was created.  If this happens, then we should not remove the machine and require the user to remove the finalizer and instruct them to check the cloud to remove the leaked instance.  This is the only way to ensure we don't leak an instance.

2020-09-07 09:33 UTC, JoelSpeed commented
> My suggestion is to check that the credentials secret exists before adding the finalizer.

This makes more sense to me now, though I do think this PR provides a pretty similar experience, we are just checking it exists before the Machine ever gets created. We don't even get to the point where the Machine could go failed, which I think is preferable. Though I appreciate the concerns about the UX of a MachineSet failing to create machines.

Personally I prefer the fail early and provide details of failed machine creates on the MachineSet YAML still, I think this could provide the plumbing/opportunity to provide more helpful information to users for the various paths as to why the MachineSet couldn't do something

2020-11-02 13:37 UTC, michaelgugino commented
We have the possibility to race with the CCO on first install.  Let's not fail machines or otherwise do things that might be helpful but cause other buggy behavior.  I suggest we close this.

2020-11-09 12:12 UTC, Danil-Grigorev requested changes
Changes look good to me, but we surely should not merge this like that, talking about https://github.com/openshift/machine-api-operator/pull/673#issuecomment-720476729. Could it be implemented using warnings instead of rejecting resource, so we just notify the user that it is not expected to have no userSecret? This should not affect cluster installation. 

Also, this PR implements passing resource client to webhooks, which is needed to fix `BZ 1889620`, so the fix is currently blocked.

2020-11-09 12:15 UTC, JoelSpeed commented
This needs picking up again as it hasn't been touched in a while, but switching to a warning could be a good way to signal to the user that something isn't quite as expected, how do others feel about that approach?

2020-11-12 14:04 UTC, michaelgugino commented
Let's drop this.  We should just indicate on machine status that the secret is not present.  In most cases it will be, in limited cases where a user makes a typo, it will be obvious how to fix it.

2020-11-12 14:09 UTC, michaelgugino commented
/hold

These webhooks are not a priority.

2020-11-30 18:27 UTC, JoelSpeed commented
/hold cancel

I've updated this to warn users when a credentials secret does not exist. This is non blocking and means that users may be alerted to a problem earlier should there be one. PTAL

2020-12-01 08:39 UTC, JoelSpeed commented
/retest

2020-12-01 10:15 UTC, Danil-Grigorev approved these changes
/approve

2020-12-10 13:41 UTC, alexander-demichev approved these changes
The change doesn't block machine from being created, looks good to me in that case

/lgtm

2020-12-10 13:57 UTC, JoelSpeed commented
/retest

2020-12-10 16:56 UTC, merged