add mapi_machinehealthcheck_short_circuit metric
openshift/machine-api-operator pull request #755
Opened 2020-11-17 20:19 UTC by elmiko

This change adds the counter metric to track when a MachineHealthCheck
has been short-circuited. It adds helper functions for enabling and
disabling the metric, and an update to the metrics doc showing the new
metric.

2020-11-17 20:19 UTC, elmiko commented
creating this as a draft while i do some testing
it will need to go after #754

2020-11-17 21:16 UTC, elmiko commented
this is ready for review but still needs to go after the other pr
/hold on #754 being merged

2020-11-18 22:00 UTC, elmiko commented
updated to add the namespace label and change the Register... func call to Observe...

2020-11-18 22:07 UTC, elmiko commented
/retest

2020-11-19 14:31 UTC, elmiko commented
/retest

2020-11-19 15:48 UTC, elmiko commented
not sure why this is causing conflicts, once #752 and #754 have merged i will rebase

2020-11-20 19:58 UTC, elmiko commented
rebased

2020-11-20 22:30 UTC, elmiko commented
/retest

2020-11-22 14:19 UTC, elmiko commented
/retest

2020-11-30 21:02 UTC, elmiko commented
rebased after merge of 754
/hold cancel

2020-12-01 15:47 UTC, elmiko commented
/retest

2020-12-01 20:17 UTC, elmiko commented
/retest

2020-12-02 14:19 UTC, elmiko commented
/retest

2020-12-02 14:30 UTC, michaelgugino requested changes
Are we sure we want to call it 'short_circuit' as that is a little idiomatic.  Is 'short circuit' described elsewhere?  We use "RemediationAllowed" as the condition, perhaps we should use that for the metric and reverse the boolean?  Or "TooManyUnhealthyNodes" to match the reason and keep the boolean the same?

If our docs say 'short circuit' I suppose that's fine, but we should try to be consistent if not.

2020-12-02 15:00 UTC, michaelgugino approved these changes
/lgtm

2020-12-02 20:49 UTC, elmiko commented
/retest

2020-12-02 21:20 UTC, elmiko commented
/retest

2020-12-03 03:31 UTC, elmiko commented
/retest

2020-12-03 14:04 UTC, JoelSpeed reviewed
/approve

2020-12-04 15:03 UTC, merged